# wrangler.toml

name = "poster-bot"
main = "src/index.js"
compatibility_date = "2024-05-10"

[[kv_namespaces]]
binding = "BOT_STATE"
id = "a6e1ceb45d08400ba4bf50ab2921abe5"

[vars]
API_BASE_URL = "https://api.telegram.org"