# wrangler.toml (Simplified and Correct Version)

name = "poster-bot"
main = "src/entry.py"
compatibility_date = "2025-08-26"

# This flag is the correct and sufficient way to enable the Python runtime.
compatibility_flags = [ "python_workers" ]

# Your KV and vars sections are correct and should be kept.
[[kv_namespaces]]
binding = "BOT_STATE"
id = "a6e1ceb45d08400ba4bf50ab2921abe5"

[vars]
API_BASE_URL = "https://api.telegram.org"